# CONFIGURACIÓN DE CONEXIÓN A ORACLE CLOUD
# Reemplaza 'nombre_de_tu_bd_tp' por el nombre del servicio TNS de tu base de datos (lo encuentras en el archivo tnsnames.ora del wallet)
spring.datasource.url=jdbc:oracle:thin:@nombre_de_tu_bd_tp?TNS_ADMIN=./src/main/resources/wallet
spring.datasource.username=TU_USUARIO_ADMIN
spring.datasource.password=TU_CONTRASEÑA

spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# CONFIGURACIÓN DE JPA / HIBERNATE
# 'update' creará la tabla PRODUCTS automáticamente si no existe
spring.jpa.hibernate.ddl-auto=update 
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect

# PUERTO DEL MICROSERVICIO
server.port=8081