spring.datasource.url=jdbc:mysql://pedidos360-db.c7cqjzbpry4w.us-east-1.rds.amazonaws.com:3306/pedidos360?createDatabaseIfNotExist=true&useSSL=true&serverTimezone=UTC
spring.datasource.username=admin
spring.datasource.password=Gonzalo1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
server.port=8081